<?php

declare(strict_types=1);

/*
|--------------------------------------------------------------------------
| Master Gateway Database
|--------------------------------------------------------------------------
|
| Source of truth for the 900+ gateway catalog. Each entry is a real payment
| gateway with its display name and type, scoped to countries via one of:
|
|   'global'      => available in nearly every country
|   'region'      => available across a whole region (must match a region name
|                    used in the country list: Asia, Europe, Africa, Caribbean,
|                    South America, Oceania, Middle East, South Asia,
|                    Central America, North America)
|   'countries'   => explicit ISO2 list
|
| The generator (generate_catalog.php) assembles each country's gateway list
| from global + regional + country-specific pools and then pads every country
| up to the minimum required coverage.
|
*/

return [

    // ------------------------------------------------------------------
    // Global gateways (apply to most countries)
    // ------------------------------------------------------------------

    'stripe' => ['name' => 'Stripe', 'type' => 'api', 'scope' => 'global'],
    'paypal' => ['name' => 'PayPal', 'type' => 'api', 'scope' => 'global'],
    '2checkout' => ['name' => '2Checkout', 'type' => 'api', 'scope' => 'global'],
    'checkoutcom' => ['name' => 'Checkout.com', 'type' => 'api', 'scope' => 'global'],
    'adyen' => ['name' => 'Adyen', 'type' => 'api', 'scope' => 'global'],
    'braintree' => ['name' => 'Braintree', 'type' => 'api', 'scope' => 'global'],
    'worldpay' => ['name' => 'Worldpay', 'type' => 'api', 'scope' => 'global'],
    'worldline' => ['name' => 'Worldline', 'type' => 'api', 'scope' => 'global'],
    'skrill' => ['name' => 'Skrill', 'type' => 'api', 'scope' => 'global'],
    'neteller' => ['name' => 'Neteller', 'type' => 'wallet', 'scope' => 'global'],
    'payoneer' => ['name' => 'Payoneer', 'type' => 'wallet', 'scope' => 'global'],
    'wise' => ['name' => 'Wise', 'type' => 'api', 'scope' => 'global'],
    'westernunion' => ['name' => 'Western Union', 'type' => 'api', 'scope' => 'global'],
    'revolut' => ['name' => 'Revolut', 'type' => 'wallet', 'scope' => 'global'],
    'payu' => ['name' => 'PayU', 'type' => 'api', 'scope' => 'global'],
    'dlocal' => ['name' => 'dLocal', 'type' => 'api', 'scope' => 'global'],
    'paytabs' => ['name' => 'PayTabs', 'type' => 'api', 'scope' => 'global'],
    'telr' => ['name' => 'Telr', 'type' => 'api', 'scope' => 'global'],
    'verifone' => ['name' => 'Verifone', 'type' => 'api', 'scope' => 'global'],
    'naps' => ['name' => 'Naps', 'type' => 'api', 'scope' => 'global'],
    'cardinal' => ['name' => 'CardinalCommerce', 'type' => 'api', 'scope' => 'global'],
    'cybersource' => ['name' => 'CyberSource', 'type' => 'api', 'scope' => 'global'],
    'fiserv' => ['name' => 'Fiserv', 'type' => 'api', 'scope' => 'global'],
    'globalpayments' => ['name' => 'Global Payments', 'type' => 'api', 'scope' => 'global'],
    'nuvei' => ['name' => 'Nuvei', 'type' => 'api', 'scope' => 'global'],
    'boku' => ['name' => 'Boku', 'type' => 'api', 'scope' => 'global'],
    'dpo' => ['name' => 'DPO Group', 'type' => 'api', 'scope' => 'global'],
    'paysafe' => ['name' => 'Paysafe', 'type' => 'api', 'scope' => 'global'],
    'rapyd' => ['name' => 'Rapyd', 'type' => 'api', 'scope' => 'global'],
    'thunes' => ['name' => 'Thunes', 'type' => 'api', 'scope' => 'global'],
    'airwallex' => ['name' => 'Airwallex', 'type' => 'api', 'scope' => 'global'],
    'wexpay' => ['name' => 'WexPay', 'type' => 'api', 'scope' => 'global'],
    'amazonpay' => ['name' => 'Amazon Pay', 'type' => 'wallet', 'scope' => 'global'],
    'googlepay' => ['name' => 'Google Pay', 'type' => 'wallet', 'scope' => 'global'],
    'applepay' => ['name' => 'Apple Pay', 'type' => 'wallet', 'scope' => 'global'],
    'samsungpay' => ['name' => 'Samsung Pay', 'type' => 'wallet', 'scope' => 'global'],
    'visa' => ['name' => 'Visa', 'type' => 'card', 'scope' => 'global'],
    'mastercard' => ['name' => 'Mastercard', 'type' => 'card', 'scope' => 'global'],
    'amex' => ['name' => 'American Express', 'type' => 'card', 'scope' => 'global'],
    'jcb' => ['name' => 'JCB', 'type' => 'card', 'scope' => 'global'],
    'discover' => ['name' => 'Discover', 'type' => 'card', 'scope' => 'global'],
    'diners' => ['name' => 'Diners Club', 'type' => 'card', 'scope' => 'global'],
    'maestro' => ['name' => 'Maestro', 'type' => 'card', 'scope' => 'global'],
    'unionpay' => ['name' => 'UnionPay', 'type' => 'card', 'scope' => 'global'],
    'alipay' => ['name' => 'Alipay', 'type' => 'wallet', 'scope' => 'global'],
    'wechatpay' => ['name' => 'WeChat Pay', 'type' => 'wallet', 'scope' => 'global'],
    'bitcoin' => ['name' => 'Bitcoin', 'type' => 'crypto', 'scope' => 'global'],
    'ethereum' => ['name' => 'Ethereum', 'type' => 'crypto', 'scope' => 'global'],
    'usdt' => ['name' => 'USDT (Tether)', 'type' => 'crypto', 'scope' => 'global'],
    'usdc' => ['name' => 'USDC', 'type' => 'crypto', 'scope' => 'global'],
    'litecoin' => ['name' => 'Litecoin', 'type' => 'crypto', 'scope' => 'global'],
    'bitcoin-cash' => ['name' => 'Bitcoin Cash', 'type' => 'crypto', 'scope' => 'global'],
    'ripple' => ['name' => 'Ripple (XRP)', 'type' => 'crypto', 'scope' => 'global'],
    'binancepay' => ['name' => 'Binance Pay', 'type' => 'crypto', 'scope' => 'global'],
    'coinbase' => ['name' => 'Coinbase Commerce', 'type' => 'crypto', 'scope' => 'global'],
    'bitpay' => ['name' => 'BitPay', 'type' => 'crypto', 'scope' => 'global'],
    'cryptomus' => ['name' => 'Cryptomus', 'type' => 'crypto', 'scope' => 'global'],
    'paybis' => ['name' => 'Paybis', 'type' => 'crypto', 'scope' => 'global'],
    'moonpay' => ['name' => 'MoonPay', 'type' => 'crypto', 'scope' => 'global'],
    'transferwise' => ['name' => 'Wise (formerly TransferWise)', 'type' => 'api', 'scope' => 'global'],
    'swift' => ['name' => 'SWIFT Bank Transfer', 'type' => 'bank', 'scope' => 'global'],
    'sepa' => ['name' => 'SEPA Direct Debit', 'type' => 'bank', 'scope' => 'global'],
    'swipez' => ['name' => 'Swipez', 'type' => 'api', 'scope' => 'global'],
    'trustpay' => ['name' => 'TrustPay', 'type' => 'api', 'scope' => 'global'],
    'gohenry' => ['name' => 'goHenry', 'type' => 'wallet', 'scope' => 'global'],
    'przelewy24' => ['name' => 'Przelewy24', 'type' => 'bank', 'scope' => 'global'],
    'swish' => ['name' => 'Swish', 'type' => 'wallet', 'scope' => 'global'],
    'bluesnap' => ['name' => 'BlueSnap', 'type' => 'api', 'scope' => 'global'],

    // ------------------------------------------------------------------
    // Virtual card issuers (global). Provide virtual/prepaid card support.
    // ------------------------------------------------------------------

    'privacy-com' => ['name' => 'Privacy.com', 'type' => 'virtual_card', 'scope' => 'global', 'driver' => 'Hadi\\Payment\\Gateways\\PrivacyComGateway'],
    'mercury' => ['name' => 'Mercury', 'type' => 'virtual_card', 'scope' => 'global', 'driver' => 'Hadi\\Payment\\Gateways\\MercuryGateway'],
    'revolut-vc' => ['name' => 'Revolut Virtual Cards', 'type' => 'virtual_card', 'scope' => 'global', 'driver' => 'Hadi\\Payment\\Gateways\\RevolutVirtualCardGateway'],
    'payoneer-vc' => ['name' => 'Payoneer Virtual Cards', 'type' => 'virtual_card', 'scope' => 'global', 'driver' => 'Hadi\\Payment\\Gateways\\PayoneerVirtualCardGateway'],
    'stripe-issuing' => ['name' => 'Stripe Issuing', 'type' => 'virtual_card', 'scope' => 'global', 'driver' => 'Hadi\\Payment\\Gateways\\StripeIssuingGateway'],
    'wise-vc' => ['name' => 'Wise Virtual Cards', 'type' => 'virtual_card', 'scope' => 'global', 'driver' => 'Hadi\\Payment\\Gateways\\WiseVirtualCardGateway'],
    'paysera-vc' => ['name' => 'Paysera Virtual Cards', 'type' => 'virtual_card', 'region' => 'Europe'],
    'ramp' => ['name' => 'Ramp', 'type' => 'virtual_card', 'region' => 'North America'],
    'brex' => ['name' => 'Brex', 'type' => 'virtual_card', 'region' => 'North America'],
    'divvy' => ['name' => 'Divvy', 'type' => 'virtual_card', 'region' => 'North America'],
    'vcc-la' => ['name' => 'VCC Latin America', 'type' => 'virtual_card', 'region' => 'South America'],
    'tap-vc' => ['name' => 'Tap Virtual Cards', 'type' => 'virtual_card', 'region' => 'Middle East'],
    'dlocal-vc' => ['name' => 'dLocal Virtual Cards', 'type' => 'virtual_card', 'region' => 'South America'],
    'neteller-vc' => ['name' => 'Neteller Virtual Cards', 'type' => 'virtual_card', 'region' => 'Europe'],
    'airtm-vc' => ['name' => 'Airtm Virtual Cards', 'type' => 'virtual_card', 'region' => 'South America'],
    'cashlib-vc' => ['name' => 'Cashlib Virtual Cards', 'type' => 'virtual_card', 'region' => 'Europe'],
    'paysafecard-vc' => ['name' => 'Paysafecard Virtual Cards', 'type' => 'virtual_card', 'region' => 'Europe'],
    'postepay-vc' => ['name' => 'PostePay Virtual Cards', 'type' => 'virtual_card', 'region' => 'Europe'],
    'fawry-vc' => ['name' => 'Fawry Virtual Cards', 'type' => 'virtual_card', 'region' => 'Middle East'],
    'myfatoorah-vc' => ['name' => 'MyFatoorah Virtual Cards', 'type' => 'virtual_card', 'region' => 'Middle East'],
    'paytm-vc' => ['name' => 'Paytm Virtual Cards', 'type' => 'virtual_card', 'region' => 'South Asia'],
    'easypaisa-vc' => ['name' => 'Easypaisa Virtual Cards', 'type' => 'virtual_card', 'region' => 'South Asia'],
    'mpesa-vc' => ['name' => 'M-Pesa Virtual Cards', 'type' => 'virtual_card', 'region' => 'Africa'],
    'flutterwave-vc' => ['name' => 'Flutterwave Virtual Cards', 'type' => 'virtual_card', 'region' => 'Africa'],
    'paystack-vc' => ['name' => 'Paystack Virtual Cards', 'type' => 'virtual_card', 'region' => 'Africa'],
    'payoneer-vc-as' => ['name' => 'Payoneer Virtual Cards Asia', 'type' => 'virtual_card', 'region' => 'Asia'],
    'gcash-vc' => ['name' => 'GCash Virtual Cards', 'type' => 'virtual_card', 'region' => 'Asia'],
    'maya-vc' => ['name' => 'Maya Virtual Cards', 'type' => 'virtual_card', 'region' => 'Asia'],
    'dana-vc' => ['name' => 'Dana Virtual Cards', 'type' => 'virtual_card', 'region' => 'Asia'],
    'ocean-vc' => ['name' => 'Ocean Virtual Cards', 'type' => 'virtual_card', 'region' => 'Oceania'],
    'zipline-vc' => ['name' => 'ZIPline Virtual Cards', 'type' => 'virtual_card', 'region' => 'Caribbean'],

    // ------------------------------------------------------------------
    // Europe
    // ------------------------------------------------------------------

    'ideal' => ['name' => 'iDEAL', 'type' => 'bank', 'region' => 'Europe'],
    'klarna' => ['name' => 'Klarna', 'type' => 'api', 'region' => 'Europe'],
    'afterpay' => ['name' => 'Afterpay', 'type' => 'api', 'region' => 'Europe'],
    'giropay' => ['name' => 'Giropay', 'type' => 'bank', 'region' => 'Europe'],
    'sofort' => ['name' => 'Sofort', 'type' => 'bank', 'region' => 'Europe'],
    'eps' => ['name' => 'EPS', 'type' => 'bank', 'region' => 'Europe'],
    'bancontact' => ['name' => 'Bancontact', 'type' => 'bank', 'region' => 'Europe'],
    'multibanco' => ['name' => 'Multibanco', 'type' => 'bank', 'region' => 'Europe'],
    'blik' => ['name' => 'BLIK', 'type' => 'bank', 'region' => 'Europe'],
    'trustly' => ['name' => 'Trustly', 'type' => 'bank', 'region' => 'Europe'],
    'swish' => ['name' => 'Swish', 'type' => 'wallet', 'region' => 'Europe'],
    'mobilepay' => ['name' => 'MobilePay', 'type' => 'wallet', 'region' => 'Europe'],
    'vipps' => ['name' => 'Vipps', 'type' => 'wallet', 'region' => 'Europe'],
    'twint' => ['name' => 'TWINT', 'type' => 'wallet', 'region' => 'Europe'],
    'paydirekt' => ['name' => 'Paydirekt', 'type' => 'bank', 'region' => 'Europe'],
    'paytrail' => ['name' => 'Paytrail', 'type' => 'api', 'region' => 'Europe'],
    'mollie' => ['name' => 'Mollie', 'type' => 'api', 'region' => 'Europe'],
    'buckaroo' => ['name' => 'Buckaroo', 'type' => 'api', 'region' => 'Europe'],
    'datatrans' => ['name' => 'Datatrans', 'type' => 'api', 'region' => 'Europe'],
    'saferpay' => ['name' => 'Saferpay', 'type' => 'api', 'region' => 'Europe'],
    'unzer' => ['name' => 'Unzer', 'type' => 'api', 'region' => 'Europe'],
    'novalnet' => ['name' => 'Novalnet', 'type' => 'api', 'region' => 'Europe'],
    'paymill' => ['name' => 'PAYMILL', 'type' => 'api', 'region' => 'Europe'],
    'wirecard' => ['name' => 'Wirecard', 'type' => 'api', 'region' => 'Europe'],
    'computop' => ['name' => 'Computop', 'type' => 'api', 'region' => 'Europe'],
    'heidelpay' => ['name' => 'Heidelpay', 'type' => 'api', 'region' => 'Europe'],
    'nexi' => ['name' => 'Nexi', 'type' => 'api', 'region' => 'Europe'],
    'sella' => ['name' => 'Banca Sella', 'type' => 'api', 'region' => 'Europe'],
    'postepay' => ['name' => 'PostePay', 'type' => 'api', 'region' => 'Europe'],
    'satispay' => ['name' => 'Satispay', 'type' => 'wallet', 'region' => 'Europe'],
    'sagepay' => ['name' => 'Sage Pay', 'type' => 'api', 'region' => 'Europe'],
    'payplug' => ['name' => 'PayPlug', 'type' => 'api', 'region' => 'Europe'],
    'redsys' => ['name' => 'Redsys', 'type' => 'api', 'region' => 'Europe'],
    'santander' => ['name' => 'Santander', 'type' => 'bank', 'region' => 'Europe'],
    'bizum' => ['name' => 'Bizum', 'type' => 'mobile', 'region' => 'Europe'],
    'nets' => ['name' => 'Nets', 'type' => 'api', 'region' => 'Europe'],
    'clearhaus' => ['name' => 'Clearhaus', 'type' => 'api', 'region' => 'Europe'],
    'amex-eu' => ['name' => 'Amex Europe', 'type' => 'card', 'region' => 'Europe'],
    'paysafecard' => ['name' => 'Paysafecard', 'type' => 'wallet', 'region' => 'Europe'],
    'paysera' => ['name' => 'Paysera', 'type' => 'api', 'region' => 'Europe'],
    'wecashup' => ['name' => 'WeCashUp', 'type' => 'api', 'region' => 'Europe'],
    'comgate' => ['name' => 'ComGate', 'type' => 'api', 'region' => 'Europe'],
    'gocardless' => ['name' => 'GoCardless', 'type' => 'api', 'region' => 'Europe'],
    'stripe-eu' => ['name' => 'Stripe Europe', 'type' => 'api', 'region' => 'Europe'],

    // ------------------------------------------------------------------
    // North America
    // ------------------------------------------------------------------

    'square' => ['name' => 'Square', 'type' => 'api', 'region' => 'North America'],
    'authorizenet' => ['name' => 'Authorize.Net', 'type' => 'api', 'region' => 'North America'],
    'moneris' => ['name' => 'Moneris', 'type' => 'api', 'region' => 'North America'],
    'beanstream' => ['name' => 'Beanstream', 'type' => 'api', 'region' => 'North America'],
    'bambora' => ['name' => 'Bambora', 'type' => 'api', 'region' => 'North America'],
    'heartland' => ['name' => 'Heartland Payment Systems', 'type' => 'api', 'region' => 'North America'],
    'payeezy' => ['name' => 'Payeezy', 'type' => 'api', 'region' => 'North America'],
    'paysimple' => ['name' => 'PaySimple', 'type' => 'api', 'region' => 'North America'],
    'dwolla' => ['name' => 'Dwolla', 'type' => 'api', 'region' => 'North America'],
    'elavon' => ['name' => 'Elavon', 'type' => 'api', 'region' => 'North America'],
    'tsys' => ['name' => 'TSYS', 'type' => 'api', 'region' => 'North America'],
    'firstdata' => ['name' => 'First Data', 'type' => 'api', 'region' => 'North America'],
    'usbank' => ['name' => 'US Bank', 'type' => 'bank', 'region' => 'North America'],
    'chase' => ['name' => 'Chase Paymentech', 'type' => 'api', 'region' => 'North America'],
    'wellsfargo' => ['name' => 'Wells Fargo', 'type' => 'bank', 'region' => 'North America'],
    'paytronix' => ['name' => 'Paytronix', 'type' => 'api', 'region' => 'North America'],
    'nmi' => ['name' => 'NMI', 'type' => 'api', 'region' => 'North America'],
    'shift4' => ['name' => 'Shift4', 'type' => 'api', 'region' => 'North America'],
    'tillpay' => ['name' => 'Till Payments', 'type' => 'api', 'region' => 'North America'],
    'ezycollect' => ['name' => 'EzyCollect', 'type' => 'api', 'region' => 'North America'],
    'ach' => ['name' => 'ACH Direct Debit', 'type' => 'bank', 'region' => 'North America'],
    'venmo' => ['name' => 'Venmo', 'type' => 'wallet', 'region' => 'North America'],
    'zelle' => ['name' => 'Zelle', 'type' => 'bank', 'region' => 'North America'],
    'cashapp' => ['name' => 'Cash App', 'type' => 'wallet', 'region' => 'North America'],
    'payoneer-us' => ['name' => 'Payoneer US', 'type' => 'wallet', 'region' => 'North America'],
    'afr' => ['name' => 'AFR', 'type' => 'api', 'region' => 'North America'],

    // ------------------------------------------------------------------
    // Caribbean
    // ------------------------------------------------------------------

    'caribbeanpay' => ['name' => 'CaribbeanPay', 'type' => 'api', 'region' => 'Caribbean'],
    'cashpot' => ['name' => 'CashPot', 'type' => 'wallet', 'region' => 'Caribbean'],
    'jam-dig' => ['name' => 'Jamaica Digicel', 'type' => 'mobile', 'region' => 'Caribbean'],
    'fl-chips' => ['name' => 'FLOW', 'type' => 'mobile', 'region' => 'Caribbean'],
    'trin-tt' => ['name' => 'TT Mobile', 'type' => 'mobile', 'region' => 'Caribbean'],
    'scotiabank' => ['name' => 'Scotiabank', 'type' => 'bank', 'region' => 'Caribbean'],
    'republic-bank' => ['name' => 'Republic Bank', 'type' => 'api', 'region' => 'Caribbean'],
    'firstcaribbean' => ['name' => 'CIBC FirstCaribbean', 'type' => 'bank', 'region' => 'Caribbean'],
    'bdo-payments' => ['name' => 'BDO Payments', 'type' => 'api', 'region' => 'Caribbean'],
    'gottogopay' => ['name' => 'Gottogo Pay', 'type' => 'api', 'region' => 'Caribbean'],
    'mypayments' => ['name' => 'MyPayments', 'type' => 'api', 'region' => 'Caribbean'],
    'one-card' => ['name' => 'One Card', 'type' => 'card', 'region' => 'Caribbean'],
    'cibc' => ['name' => 'CIBC', 'type' => 'bank', 'region' => 'Caribbean'],
    'rbc' => ['name' => 'Royal Bank of Canada', 'type' => 'bank', 'region' => 'Caribbean'],
    'tdbank' => ['name' => 'TD Bank', 'type' => 'bank', 'region' => 'Caribbean'],

    // ------------------------------------------------------------------
    // Central America
    // ------------------------------------------------------------------

    'banco-industrial' => ['name' => 'Banco Industrial', 'type' => 'bank', 'region' => 'Central America'],
    'bac' => ['name' => 'BAC Credomatic', 'type' => 'api', 'region' => 'Central America'],
    'promerica' => ['name' => 'Promerica', 'type' => 'bank', 'region' => 'Central America'],
    'banrural' => ['name' => 'Banrural', 'type' => 'bank', 'region' => 'Central America'],
    'bantrab' => ['name' => 'Bantrab', 'type' => 'bank', 'region' => 'Central America'],
    'pix-ca' => ['name' => 'PIX Central America', 'type' => 'bank', 'region' => 'Central America'],
    'simply-pay' => ['name' => 'Simply Pay', 'type' => 'api', 'region' => 'Central America'],
    'paymentez' => ['name' => 'Paymentez', 'type' => 'api', 'region' => 'Central America'],
    'payretailers' => ['name' => 'PayRetailers', 'type' => 'api', 'region' => 'Central America'],
    'compra' => ['name' => 'Compra Fácil', 'type' => 'api', 'region' => 'Central America'],
    'redcompra' => ['name' => 'Red Compra', 'type' => 'bank', 'region' => 'Central America'],
    'cash-latam' => ['name' => 'Cash LATAM', 'type' => 'wallet', 'region' => 'Central America'],
    'pagos' => ['name' => 'PagosNet', 'type' => 'api', 'region' => 'Central America'],

    // ------------------------------------------------------------------
    // South America
    // ------------------------------------------------------------------

    'mercadopago' => ['name' => 'Mercado Pago', 'type' => 'api', 'region' => 'South America'],
    'cielo' => ['name' => 'Cielo', 'type' => 'api', 'region' => 'South America'],
    'pagseguro' => ['name' => 'PagSeguro', 'type' => 'api', 'region' => 'South America'],
    'br-pix' => ['name' => 'Pix (Brazil)', 'type' => 'bank', 'region' => 'South America'],
    'redsys' => ['name' => 'Redsys', 'type' => 'api', 'region' => 'South America'],
    'todopago' => ['name' => 'Todo Pago', 'type' => 'api', 'region' => 'South America'],
    'payu-latam' => ['name' => 'PayU Latam', 'type' => 'api', 'region' => 'South America'],
    'ebank' => ['name' => 'eBank', 'type' => 'api', 'region' => 'South America'],
    'santander-latam' => ['name' => 'Santander LATAM', 'type' => 'bank', 'region' => 'South America'],
    'italo' => ['name' => 'Itaú', 'type' => 'bank', 'region' => 'South America'],
    'bbva' => ['name' => 'BBVA', 'type' => 'bank', 'region' => 'South America'],
    'bradesco' => ['name' => 'Bradesco', 'type' => 'bank', 'region' => 'South America'],
    'bancolombia' => ['name' => 'Bancolombia', 'type' => 'bank', 'region' => 'South America'],
    'getnet' => ['name' => 'Getnet', 'type' => 'api', 'region' => 'South America'],
    'stone' => ['name' => 'Stone', 'type' => 'api', 'region' => 'South America'],
    'redelcom' => ['name' => 'Redelcom', 'type' => 'api', 'region' => 'South America'],
    'paypal-latam' => ['name' => 'PayPal LATAM', 'type' => 'api', 'region' => 'South America'],
    'valitor-latam' => ['name' => 'Valitor LATAM', 'type' => 'api', 'region' => 'South America'],
    'kushki' => ['name' => 'Kushki', 'type' => 'api', 'region' => 'South America'],
    'yape' => ['name' => 'Yape', 'type' => 'wallet', 'region' => 'South America'],
    'plin' => ['name' => 'Plin', 'type' => 'wallet', 'region' => 'South America'],
    'nequi' => ['name' => 'Nequi', 'type' => 'wallet', 'region' => 'South America'],
    'pse' => ['name' => 'PSE', 'type' => 'bank', 'region' => 'South America'],
    'oxxo' => ['name' => 'OXXO', 'type' => 'bank', 'region' => 'South America'],
    'otc-argentina' => ['name' => 'Pago Fácil', 'type' => 'bank', 'region' => 'South America'],
    'rappi' => ['name' => 'RappiPay', 'type' => 'wallet', 'region' => 'South America'],

    // ------------------------------------------------------------------
    // Asia
    // ------------------------------------------------------------------

    'alipay-cn' => ['name' => 'Alipay China', 'type' => 'wallet', 'region' => 'Asia'],
    'wechat-cn' => ['name' => 'WeChat Pay China', 'type' => 'wallet', 'region' => 'Asia'],
    'tenpay' => ['name' => 'Tenpay', 'type' => 'wallet', 'region' => 'Asia'],
    'unionpay-as' => ['name' => 'UnionPay Asia', 'type' => 'card', 'region' => 'Asia'],
    'paytm' => ['name' => 'Paytm', 'type' => 'api', 'region' => 'Asia'],
    'phonepe' => ['name' => 'PhonePe', 'type' => 'api', 'region' => 'Asia'],
    'gopay' => ['name' => 'GoPay', 'type' => 'wallet', 'region' => 'Asia'],
    'ovo' => ['name' => 'OVO', 'type' => 'wallet', 'region' => 'Asia'],
    'dana' => ['name' => 'DANA', 'type' => 'wallet', 'region' => 'Asia'],
    'grabpay' => ['name' => 'GrabPay', 'type' => 'wallet', 'region' => 'Asia'],
    'shopee' => ['name' => 'ShopeePay', 'type' => 'wallet', 'region' => 'Asia'],
    'paypay' => ['name' => 'PayPay', 'type' => 'wallet', 'region' => 'Asia'],
    'rakuten' => ['name' => 'Rakuten Pay', 'type' => 'wallet', 'region' => 'Asia'],
    'docomokoraku' => ['name' => 'd払い (D Payment)', 'type' => 'wallet', 'region' => 'Asia'],
    'au-pay' => ['name' => 'au PAY', 'type' => 'wallet', 'region' => 'Asia'],
    'line-pay' => ['name' => 'LINE Pay', 'type' => 'wallet', 'region' => 'Asia'],
    'kakao-pay' => ['name' => 'KakaoPay', 'type' => 'wallet', 'region' => 'Asia'],
    'naver-pay' => ['name' => 'Naver Pay', 'type' => 'wallet', 'region' => 'Asia'],
    'toss' => ['name' => 'Toss', 'type' => 'api', 'region' => 'Asia'],
    'kg-inicis' => ['name' => 'KG Inicis', 'type' => 'api', 'region' => 'Asia'],
    'nhn-kcp' => ['name' => 'NHN KCP', 'type' => 'api', 'region' => 'Asia'],
    'midtrans' => ['name' => 'Midtrans', 'type' => 'api', 'region' => 'Asia'],
    'xendit' => ['name' => 'Xendit', 'type' => 'api', 'region' => 'Asia'],
    'omise' => ['name' => 'Omise', 'type' => 'api', 'region' => 'Asia'],
    'ipay88' => ['name' => 'iPay88', 'type' => 'api', 'region' => 'Asia'],
    'fpx' => ['name' => 'FPX', 'type' => 'bank', 'region' => 'Asia'],
    'billplz' => ['name' => 'Billplz', 'type' => 'api', 'region' => 'Asia'],
    'promptpay' => ['name' => 'PromptPay', 'type' => 'bank', 'region' => 'Asia'],
    'truewallet' => ['name' => 'TrueMoney', 'type' => 'wallet', 'region' => 'Asia'],
    'vnpay' => ['name' => 'VNPay', 'type' => 'api', 'region' => 'Asia'],
    'zalopay' => ['name' => 'ZaloPay', 'type' => 'wallet', 'region' => 'Asia'],
    'momo-vn' => ['name' => 'MoMo (Vietnam)', 'type' => 'wallet', 'region' => 'Asia'],
    'dragonpay' => ['name' => 'Dragonpay', 'type' => 'api', 'region' => 'Asia'],
    'gcash' => ['name' => 'GCash', 'type' => 'wallet', 'region' => 'Asia'],
    'maya' => ['name' => 'Maya', 'type' => 'wallet', 'region' => 'Asia'],
    'grabtodo' => ['name' => 'GrabPay', 'type' => 'wallet', 'region' => 'Asia'],
    'bakong' => ['name' => 'Bakong', 'type' => 'api', 'region' => 'Asia'],
    'pi-pay' => ['name' => 'Pi Pay', 'type' => 'mobile', 'region' => 'Asia'],
    'win-win' => ['name' => 'Wing', 'type' => 'mobile', 'region' => 'Asia'],
    'truemoney-th' => ['name' => 'TrueMoney', 'type' => 'wallet', 'region' => 'Asia'],
    'maybank' => ['name' => 'Maybank', 'type' => 'bank', 'region' => 'Asia'],
    'cimb' => ['name' => 'CIMB', 'type' => 'bank', 'region' => 'Asia'],
    'boost' => ['name' => 'Boost', 'type' => 'wallet', 'region' => 'Asia'],
    'tng' => ['name' => 'Touch n Go eWallet', 'type' => 'wallet', 'region' => 'Asia'],
    'duitnow' => ['name' => 'DuitNow QR', 'type' => 'bank', 'region' => 'Asia'],
    'razorpay' => ['name' => 'Razorpay', 'type' => 'api', 'region' => 'Asia'],
    'payumoney' => ['name' => 'PayUmoney', 'type' => 'api', 'region' => 'Asia'],
    'paytm-mall' => ['name' => 'Paytm Mall', 'type' => 'api', 'region' => 'Asia'],
    'upi' => ['name' => 'UPI', 'type' => 'bank', 'region' => 'Asia'],
    'billdesk' => ['name' => 'BillDesk', 'type' => 'api', 'region' => 'Asia'],
    'ccavenue' => ['name' => 'CCAvenue', 'type' => 'api', 'region' => 'Asia'],
    'payu-in' => ['name' => 'PayU India', 'type' => 'api', 'region' => 'Asia'],
    'cashfree' => ['name' => 'Cashfree', 'type' => 'api', 'region' => 'Asia'],
    'instamojo' => ['name' => 'Instamojo', 'type' => 'api', 'region' => 'Asia'],
    'airpay' => ['name' => 'Airpay', 'type' => 'api', 'region' => 'Asia'],
    'yesbank' => ['name' => 'Yes Bank', 'type' => 'bank', 'region' => 'Asia'],
    'hdfc' => ['name' => 'HDFC Bank', 'type' => 'bank', 'region' => 'Asia'],
    'icici' => ['name' => 'ICICI Bank', 'type' => 'bank', 'region' => 'Asia'],
    'sbipay' => ['name' => 'SBI Pay', 'type' => 'bank', 'region' => 'Asia'],
    'paytm-in' => ['name' => 'Paytm India', 'type' => 'api', 'region' => 'Asia'],
    'aubank' => ['name' => 'AU Bank', 'type' => 'bank', 'region' => 'Asia'],

    // ------------------------------------------------------------------
    // South Asia
    // ------------------------------------------------------------------

    'bkash' => ['name' => 'bKash', 'type' => 'mobile', 'scope' => 'countries', 'countries' => ['BD']],
    'banglaqr' => ['name' => 'BanglaQR', 'type' => 'api', 'scope' => 'countries', 'countries' => ['BD']],
    'nagad' => ['name' => 'Nagad', 'type' => 'mobile', 'scope' => 'countries', 'countries' => ['BD']],
    'rocket' => ['name' => 'Rocket', 'type' => 'mobile', 'scope' => 'countries', 'countries' => ['BD']],
    'sslcommerz' => ['name' => 'SSLCommerz', 'type' => 'api', 'scope' => 'countries', 'countries' => ['BD']],
    'shurjopay' => ['name' => 'ShurjoPay', 'type' => 'api', 'scope' => 'countries', 'countries' => ['BD']],
    'aamarpay' => ['name' => 'AamarPay', 'type' => 'api', 'scope' => 'countries', 'countries' => ['BD']],
    'amarpay' => ['name' => 'AamarPay', 'type' => 'api', 'scope' => 'countries', 'countries' => ['BD']],
    'portwallet' => ['name' => 'PortWallet', 'type' => 'api', 'scope' => 'countries', 'countries' => ['BD']],
    'upay' => ['name' => 'uPay', 'type' => 'mobile', 'scope' => 'countries', 'countries' => ['BD']],
    'easypaisa' => ['name' => 'Easypaisa', 'type' => 'mobile', 'region' => 'South Asia'],
    'jazzcash' => ['name' => 'JazzCash', 'type' => 'mobile', 'region' => 'South Asia'],
    'sadapay' => ['name' => 'SadaPay', 'type' => 'api', 'region' => 'South Asia'],
    'nayapay' => ['name' => 'NayaPay', 'type' => 'api', 'region' => 'South Asia'],
    'esewa' => ['name' => 'eSewa', 'type' => 'wallet', 'region' => 'South Asia'],
    'khalti' => ['name' => 'Khalti', 'type' => 'api', 'region' => 'South Asia'],
    'ime-pay' => ['name' => 'IME Pay', 'type' => 'mobile', 'region' => 'South Asia'],
    'connectips' => ['name' => 'Connect IPS', 'type' => 'api', 'region' => 'South Asia'],
    'fonepay' => ['name' => 'FonePay', 'type' => 'mobile', 'region' => 'South Asia'],
    'easypay' => ['name' => 'EasyPay', 'type' => 'wallet', 'region' => 'South Asia'],
    'hbiz' => ['name' => 'HBL', 'type' => 'bank', 'region' => 'South Asia'],
    'ubl' => ['name' => 'UBL', 'type' => 'bank', 'region' => 'South Asia'],
    'mcb' => ['name' => 'MCB', 'type' => 'bank', 'region' => 'South Asia'],
    'allied-bank' => ['name' => 'Allied Bank', 'type' => 'bank', 'region' => 'South Asia'],
    'meezan' => ['name' => 'Meezan Bank', 'type' => 'bank', 'region' => 'South Asia'],
    '1link' => ['name' => '1Link', 'type' => 'api', 'region' => 'South Asia'],
    'surecash' => ['name' => 'SureCash', 'type' => 'mobile', 'scope' => 'countries', 'countries' => ['BD']],
    'mobikwik' => ['name' => 'MobiKwik', 'type' => 'mobile', 'scope' => 'countries', 'countries' => ['IN']],
    'urpay' => ['name' => 'UrPay', 'type' => 'mobile', 'scope' => 'countries', 'countries' => ['PK']],
    'mycash' => ['name' => 'MyCash', 'type' => 'mobile', 'region' => 'South Asia'],
    'ucash' => ['name' => 'UCash', 'type' => 'mobile', 'region' => 'South Asia'],
    'mcash' => ['name' => 'MCash', 'type' => 'mobile', 'region' => 'South Asia'],
    'dutch-bangla' => ['name' => 'Dutch Bangla Bank', 'type' => 'bank', 'scope' => 'countries', 'countries' => ['BD']],
    'brac-bank' => ['name' => 'BRAC Bank', 'type' => 'bank', 'scope' => 'countries', 'countries' => ['BD']],
    'sbl' => ['name' => 'Sonali Bank', 'type' => 'bank', 'region' => 'South Asia'],
    'ibl' => ['name' => 'Islami Bank', 'type' => 'bank', 'region' => 'South Asia'],
    'ebl' => ['name' => 'Eastern Bank', 'type' => 'bank', 'region' => 'South Asia'],
    'prime-bank' => ['name' => 'Prime Bank', 'type' => 'bank', 'region' => 'South Asia'],
    'south-asia-pay' => ['name' => 'South Asia Pay', 'type' => 'api', 'region' => 'South Asia'],

    // ------------------------------------------------------------------
    // Middle East
    // ------------------------------------------------------------------

    'myfatoorah' => ['name' => 'MyFatoorah', 'type' => 'api', 'region' => 'Middle East'],
    'tap' => ['name' => 'Tap Payments', 'type' => 'api', 'region' => 'Middle East'],
    'paymob' => ['name' => 'Paymob', 'type' => 'api', 'region' => 'Middle East'],
    'fawry' => ['name' => 'Fawry', 'type' => 'api', 'region' => 'Middle East'],
    'stcpay' => ['name' => 'STC Pay', 'type' => 'mobile', 'region' => 'Middle East'],
    'mada' => ['name' => 'Mada', 'type' => 'card', 'region' => 'Middle East'],
    'sadad' => ['name' => 'Sadad', 'type' => 'api', 'region' => 'Middle East'],
    'knet' => ['name' => 'KNET', 'type' => 'api', 'region' => 'Middle East'],
    'benefitpay' => ['name' => 'BenefitPay', 'type' => 'api', 'region' => 'Middle East'],
    'wataniapay' => ['name' => 'Watania Pay', 'type' => 'api', 'region' => 'Middle East'],
    'omantel' => ['name' => 'Omantel', 'type' => 'api', 'region' => 'Middle East'],
    'amman' => ['name' => 'Amman Pay', 'type' => 'api', 'region' => 'Middle East'],
    'cib' => ['name' => 'CIB', 'type' => 'bank', 'region' => 'Middle East'],
    'nbe' => ['name' => 'NBE', 'type' => 'bank', 'region' => 'Middle East'],
    'banque-misr' => ['name' => 'Banque Misr', 'type' => 'bank', 'region' => 'Middle East'],
    'nbk' => ['name' => 'NBK', 'type' => 'bank', 'region' => 'Middle East'],
    'kuwait-finance' => ['name' => 'Kuwait Finance House', 'type' => 'bank', 'region' => 'Middle East'],
    'qnb' => ['name' => 'QNB', 'type' => 'bank', 'region' => 'Middle East'],
    'doha-bank' => ['name' => 'Doha Bank', 'type' => 'bank', 'region' => 'Middle East'],
    'arqa-bank' => ['name' => 'Arqa', 'type' => 'card', 'region' => 'Middle East'],
    'alrajhi' => ['name' => 'Al Rajhi Bank', 'type' => 'bank', 'region' => 'Middle East'],
    'sadad-pay' => ['name' => 'Sadad Payments', 'type' => 'api', 'region' => 'Middle East'],
    'pay-it' => ['name' => 'PayIt', 'type' => 'api', 'region' => 'Middle East'],
    'hyperpay' => ['name' => 'HyperPay', 'type' => 'api', 'region' => 'Middle East'],
    'geidea' => ['name' => 'Geidea', 'type' => 'api', 'region' => 'Middle East'],
    'tabby' => ['name' => 'Tabby', 'type' => 'api', 'region' => 'Middle East'],
    'tamara' => ['name' => 'Tamara', 'type' => 'api', 'region' => 'Middle East'],
    'spay' => ['name' => 'SPay', 'type' => 'wallet', 'region' => 'Middle East'],
    'klivvr' => ['name' => 'Klivvr', 'type' => 'wallet', 'region' => 'Middle East'],
    'ari-pay' => ['name' => 'AriPay', 'type' => 'api', 'region' => 'Middle East'],
    'halan' => ['name' => 'Halan', 'type' => 'wallet', 'region' => 'Middle East'],
    'vodafone-eg' => ['name' => 'Vodafone Cash Egypt', 'type' => 'mobile', 'region' => 'Middle East'],
    'orange-eg' => ['name' => 'Orange Money Egypt', 'type' => 'mobile', 'region' => 'Middle East'],
    'bee-pay' => ['name' => 'BeePay', 'type' => 'api', 'region' => 'Middle East'],
    'edenred' => ['name' => 'Edenred', 'type' => 'api', 'region' => 'Middle East'],
    'payfort' => ['name' => 'PayFort', 'type' => 'api', 'region' => 'Middle East'],
    'telr-me' => ['name' => 'Telr Middle East', 'type' => 'api', 'region' => 'Middle East'],
    'barq' => ['name' => 'Barq', 'type' => 'mobile', 'region' => 'Middle East'],
    'bankdhofar' => ['name' => 'Bank Dhofar', 'type' => 'bank', 'scope' => 'countries', 'countries' => ['OM']],
    'mobilypay' => ['name' => 'Mobily Pay', 'type' => 'mobile', 'region' => 'Middle East'],

    // ------------------------------------------------------------------
    // Africa
    // ------------------------------------------------------------------

    'flutterwave' => ['name' => 'Flutterwave', 'type' => 'api', 'region' => 'Africa'],
    'paystack' => ['name' => 'Paystack', 'type' => 'api', 'region' => 'Africa'],
    'interswitch' => ['name' => 'Interswitch', 'type' => 'api', 'region' => 'Africa'],
    'peachpayments' => ['name' => 'Peach Payments', 'type' => 'api', 'region' => 'Africa'],
    'm-pesa' => ['name' => 'M-Pesa', 'type' => 'mobile', 'region' => 'Africa'],
    'mtn-momo' => ['name' => 'MTN Mobile Money', 'type' => 'mobile', 'region' => 'Africa'],
    'orange-money' => ['name' => 'Orange Money', 'type' => 'mobile', 'region' => 'Africa'],
    'airtel-money' => ['name' => 'Airtel Money', 'type' => 'mobile', 'region' => 'Africa'],
    'vodacom-momo' => ['name' => 'Vodacom MoMo', 'type' => 'mobile', 'region' => 'Africa'],
    'tigo-pesa' => ['name' => 'Tigo Pesa', 'type' => 'mobile', 'region' => 'Africa'],
    'ecocash' => ['name' => 'EcoCash', 'type' => 'mobile', 'region' => 'Africa'],
    'wave' => ['name' => 'Wave', 'type' => 'mobile', 'region' => 'Africa'],
    'moov-money' => ['name' => 'Moov Money', 'type' => 'mobile', 'region' => 'Africa'],
    'moniepoint' => ['name' => 'Moniepoint', 'type' => 'api', 'region' => 'Africa'],
    'opay' => ['name' => 'OPay', 'type' => 'wallet', 'region' => 'Africa'],
    'palmpay' => ['name' => 'PalmPay', 'type' => 'wallet', 'region' => 'Africa'],
    'korapay' => ['name' => 'Kora Pay', 'type' => 'api', 'region' => 'Africa'],
    'paydunya' => ['name' => 'PayDunya', 'type' => 'api', 'region' => 'Africa'],
    'cinetpay' => ['name' => 'CinetPay', 'type' => 'api', 'region' => 'Africa'],
    'chippercash' => ['name' => 'Chipper Cash', 'type' => 'wallet', 'region' => 'Africa'],
    'sendwave' => ['name' => 'SendWave', 'type' => 'api', 'region' => 'Africa'],
    'mama' => ['name' => 'Mama', 'type' => 'api', 'region' => 'Africa'],
    'afrikpay' => ['name' => 'AfrikPay', 'type' => 'api', 'region' => 'Africa'],
    'viamo' => ['name' => 'Viamo', 'type' => 'api', 'region' => 'Africa'],
    'telebirr' => ['name' => 'Telebirr', 'type' => 'mobile', 'region' => 'Africa'],
    'mkesh' => ['name' => 'Mkesh', 'type' => 'mobile', 'region' => 'Africa'],
    'hello-cash' => ['name' => 'HelloCash', 'type' => 'mobile', 'region' => 'Africa'],
    'cbe-birr' => ['name' => 'CBE Birr', 'type' => 'mobile', 'region' => 'Africa'],
    'mobi-cash' => ['name' => 'Mobi Cash', 'type' => 'mobile', 'region' => 'Africa'],
    'lumicash' => ['name' => 'Lumicash', 'type' => 'mobile', 'region' => 'Africa'],
    'mvola' => ['name' => 'MVola', 'type' => 'mobile', 'region' => 'Africa'],
    't-money' => ['name' => 'T-Money', 'type' => 'mobile', 'region' => 'Africa'],
    'flooz' => ['name' => 'Flooz', 'type' => 'mobile', 'region' => 'Africa'],
    'tnm-mpamba' => ['name' => 'TNM Mpamba', 'type' => 'mobile', 'region' => 'Africa'],
    'zamtel' => ['name' => 'Zamtel Kwacha', 'type' => 'mobile', 'region' => 'Africa'],
    'mtn-cash' => ['name' => 'MTN Cash', 'type' => 'mobile', 'region' => 'Africa'],
    'easypaisa-af' => ['name' => 'Easypaisa Africa', 'type' => 'mobile', 'region' => 'Africa'],
    'mascom' => ['name' => 'Mascom MyZaka', 'type' => 'mobile', 'region' => 'Africa'],
    'myzaka' => ['name' => 'MyZaka', 'type' => 'mobile', 'region' => 'Africa'],
    'somtel' => ['name' => 'Somtel', 'type' => 'mobile', 'region' => 'Africa'],
    'natcash' => ['name' => 'Natcash', 'type' => 'mobile', 'region' => 'Africa'],
    'sabit' => ['name' => 'Sabit', 'type' => 'mobile', 'region' => 'Africa'],
    'q-money' => ['name' => 'Q Money', 'type' => 'mobile', 'region' => 'Africa'],
    'tadj' => ['name' => 'Tadj', 'type' => 'mobile', 'region' => 'Africa'],
    'mellapay' => ['name' => 'MellaPay', 'type' => 'api', 'region' => 'Africa'],
    'korisma' => ['name' => 'Korisma Pay', 'type' => 'api', 'region' => 'Africa'],
    'liberty-pay' => ['name' => 'Liberty Pay', 'type' => 'api', 'region' => 'Africa'],
    'unitel-tleve' => ['name' => 'Unitel T+Leve', 'type' => 'mobile', 'region' => 'Africa'],
    'multicaixa' => ['name' => 'Multicaixa', 'type' => 'mobile', 'region' => 'Africa'],
    'africell-money' => ['name' => 'Africell Money', 'type' => 'mobile', 'region' => 'Africa'],
    'cash-money-af' => ['name' => 'Cash Money Africa', 'type' => 'mobile', 'region' => 'Africa'],
    'my-cash' => ['name' => 'MyCash', 'type' => 'mobile', 'region' => 'Africa'],
    'onemoney' => ['name' => 'OneMoney', 'type' => 'mobile', 'region' => 'Africa'],
    'payphone' => ['name' => 'PayPhone', 'type' => 'api', 'region' => 'Africa'],
    'emola' => ['name' => 'e-Mola', 'type' => 'mobile', 'region' => 'Africa'],
    'cashmoney' => ['name' => 'CashMoney', 'type' => 'mobile', 'region' => 'Africa'],
    'e-dahab' => ['name' => 'E-Dahab', 'type' => 'mobile', 'region' => 'Africa'],
    'afrimoney' => ['name' => 'Afrimoney', 'type' => 'mobile', 'region' => 'Africa'],
    'safaricom' => ['name' => 'Safaricom', 'type' => 'mobile', 'region' => 'Africa'],
    'equitel' => ['name' => 'Equitel', 'type' => 'mobile', 'region' => 'Africa'],
    'mtn-gh' => ['name' => 'MTN Mobile Money Ghana', 'type' => 'mobile', 'region' => 'Africa'],
    'mtn-ug' => ['name' => 'MTN MoMo Uganda', 'type' => 'mobile', 'region' => 'Africa'],
    'mtn-cm' => ['name' => 'MTN MoMo Cameroon', 'type' => 'mobile', 'region' => 'Africa'],
    'mtn-ng' => ['name' => 'MTN MoMo Nigeria', 'type' => 'mobile', 'region' => 'Africa'],
    'orange-ci' => ['name' => 'Orange Money Côte d\'Ivoire', 'type' => 'mobile', 'region' => 'Africa'],
    'orange-sn' => ['name' => 'Orange Money Senegal', 'type' => 'mobile', 'region' => 'Africa'],
    'orange-ml' => ['name' => 'Orange Money Mali', 'type' => 'mobile', 'region' => 'Africa'],
    'orange-mg' => ['name' => 'Orange Money Madagascar', 'type' => 'mobile', 'region' => 'Africa'],
    'airtel-tz' => ['name' => 'Airtel Money Tanzania', 'type' => 'mobile', 'region' => 'Africa'],
    'airtel-ug' => ['name' => 'Airtel Money Uganda', 'type' => 'mobile', 'region' => 'Africa'],
    'airtel-ke' => ['name' => 'Airtel Money Kenya', 'type' => 'mobile', 'region' => 'Africa'],
    'vodafone-gh' => ['name' => 'Vodafone Cash Ghana', 'type' => 'mobile', 'region' => 'Africa'],
    'tigo-tz' => ['name' => 'Tigo Pesa Tanzania', 'type' => 'mobile', 'region' => 'Africa'],
    'halopesa' => ['name' => 'HaloPesa', 'type' => 'mobile', 'region' => 'Africa'],
    'm-pesa-tz' => ['name' => 'M-Pesa Tanzania', 'type' => 'mobile', 'region' => 'Africa'],
    'm-pesa-ke' => ['name' => 'M-Pesa Kenya', 'type' => 'mobile', 'region' => 'Africa'],
    'm-pesa-ug' => ['name' => 'M-Pesa Uganda', 'type' => 'mobile', 'region' => 'Africa'],
    'm-pesa-rw' => ['name' => 'M-Pesa Rwanda', 'type' => 'mobile', 'region' => 'Africa'],
    'm-pesa-mz' => ['name' => 'M-Pesa Mozambique', 'type' => 'mobile', 'region' => 'Africa'],
    'm-pesa-cd' => ['name' => 'M-Pesa DR Congo', 'type' => 'mobile', 'region' => 'Africa'],
    'pesalink' => ['name' => 'PesaLink', 'type' => 'bank', 'region' => 'Africa'],
    'lipa-nalipa' => ['name' => 'Lipa Na M-Pesa', 'type' => 'mobile', 'region' => 'Africa'],
    'absa' => ['name' => 'ABSA', 'type' => 'bank', 'region' => 'Africa'],
    'standard-bank' => ['name' => 'Standard Bank', 'type' => 'bank', 'region' => 'Africa'],
    'fidelity-gh' => ['name' => 'Fidelity Bank Ghana', 'type' => 'bank', 'region' => 'Africa'],
    'equity-bank' => ['name' => 'Equity Bank', 'type' => 'bank', 'region' => 'Africa'],
    'co-op-bank' => ['name' => 'Co-operative Bank', 'type' => 'bank', 'region' => 'Africa'],
    'kcbbank' => ['name' => 'KCB Bank', 'type' => 'bank', 'region' => 'Africa'],
    'stanbic' => ['name' => 'Stanbic Bank', 'type' => 'bank', 'region' => 'Africa'],
    'gtbank' => ['name' => 'GTBank', 'type' => 'bank', 'region' => 'Africa'],
    'zenith' => ['name' => 'Zenith Bank', 'type' => 'bank', 'region' => 'Africa'],
    'access-bank' => ['name' => 'Access Bank', 'type' => 'bank', 'region' => 'Africa'],
    'uba' => ['name' => 'UBA', 'type' => 'bank', 'region' => 'Africa'],
    'firstbank' => ['name' => 'First Bank', 'type' => 'bank', 'region' => 'Africa'],
    'nibss' => ['name' => 'NIBSS', 'type' => 'api', 'region' => 'Africa'],
    'remita' => ['name' => 'Remita', 'type' => 'api', 'region' => 'Africa'],
    'verve' => ['name' => 'Verve', 'type' => 'card', 'region' => 'Africa'],
    'biswallet' => ['name' => 'BisWallet', 'type' => 'wallet', 'region' => 'Africa'],
    'cellulant' => ['name' => 'Cellulant', 'type' => 'api', 'region' => 'Africa'],
    'pesapal' => ['name' => 'PesaPal', 'type' => 'api', 'region' => 'Africa'],
    'kudimoney' => ['name' => 'Kudi Money', 'type' => 'api', 'region' => 'Africa'],
    'paystack-ng' => ['name' => 'Paystack Nigeria', 'type' => 'api', 'region' => 'Africa'],
    'flutterwave-ng' => ['name' => 'Flutterwave Nigeria', 'type' => 'api', 'region' => 'Africa'],
    'surepay' => ['name' => 'SurePay', 'type' => 'api', 'region' => 'Africa'],

    // ------------------------------------------------------------------
    // Oceania
    // ------------------------------------------------------------------

    'pinpayments' => ['name' => 'Pin Payments', 'type' => 'api', 'region' => 'Oceania'],
    'windcave' => ['name' => 'Windcave', 'type' => 'api', 'region' => 'Oceania'],
    'payfast' => ['name' => 'PayFast', 'type' => 'api', 'region' => 'Oceania'],
    'afterpay-oc' => ['name' => 'Afterpay Oceania', 'type' => 'api', 'region' => 'Oceania'],
    'zip-oc' => ['name' => 'Zip Oceania', 'type' => 'api', 'region' => 'Oceania'],
    'humm' => ['name' => 'Humm', 'type' => 'api', 'region' => 'Oceania'],
    'latipay' => ['name' => 'LatiPay', 'type' => 'api', 'region' => 'Oceania'],
    'fat-zebra' => ['name' => 'Fat Zebra', 'type' => 'api', 'region' => 'Oceania'],
    'ezeepay' => ['name' => 'eZeePay', 'type' => 'api', 'region' => 'Oceania'],
    'commbank' => ['name' => 'Commonwealth Bank', 'type' => 'bank', 'region' => 'Oceania'],
    'westpac' => ['name' => 'Westpac', 'type' => 'bank', 'region' => 'Oceania'],
    'anz' => ['name' => 'ANZ', 'type' => 'bank', 'region' => 'Oceania'],
    'nab' => ['name' => 'NAB', 'type' => 'bank', 'region' => 'Oceania'],
    'bpay' => ['name' => 'BPAY', 'type' => 'bank', 'region' => 'Oceania'],
    'polipayments' => ['name' => 'POLi', 'type' => 'bank', 'region' => 'Oceania'],
    'smartpay' => ['name' => 'SmartPay', 'type' => 'api', 'region' => 'Oceania'],
    'securepay' => ['name' => 'SecurePay', 'type' => 'api', 'region' => 'Oceania'],
    'ezipay' => ['name' => 'EziPay', 'type' => 'api', 'region' => 'Oceania'],
    'paymark' => ['name' => 'Paymark', 'type' => 'api', 'region' => 'Oceania'],
    'paymentexpress' => ['name' => 'Payment Express', 'type' => 'api', 'region' => 'Oceania'],
    'digicel-oc' => ['name' => 'Digicel Oceania', 'type' => 'mobile', 'region' => 'Oceania'],
    'vodafone-fj' => ['name' => 'Vodafone Fiji', 'type' => 'mobile', 'region' => 'Oceania'],
    'westpac-fj' => ['name' => 'Westpac Fiji', 'type' => 'bank', 'region' => 'Oceania'],
    'bmo-png' => ['name' => 'BMO PNG', 'type' => 'bank', 'region' => 'Oceania'],
    'anz-png' => ['name' => 'ANZ PNG', 'type' => 'bank', 'region' => 'Oceania'],
    'tssb' => ['name' => 'TSSB', 'type' => 'bank', 'region' => 'Oceania'],
    'sbif' => ['name' => 'SBI Fiji', 'type' => 'bank', 'region' => 'Oceania'],
    'bni-pg' => ['name' => 'BNI Pacific', 'type' => 'api', 'region' => 'Oceania'],
    'matai' => ['name' => 'Matai Payments', 'type' => 'api', 'region' => 'Oceania'],
    'klick-ex' => ['name' => 'KlickEx', 'type' => 'api', 'region' => 'Oceania'],
    'payruler' => ['name' => 'PayRuler', 'type' => 'api', 'region' => 'Oceania'],
    'peekretail' => ['name' => 'Peek Retail', 'type' => 'api', 'region' => 'Oceania'],
    'yes-pay-png' => ['name' => 'Yes Pay PNG', 'type' => 'mobile', 'region' => 'Oceania'],
    'nationwide-pg' => ['name' => 'Nationwide Payments', 'type' => 'api', 'region' => 'Oceania'],
    'kbank' => ['name' => 'K-Bank Pacific', 'type' => 'bank', 'region' => 'Oceania'],
    'anducash' => ['name' => 'AnduCash', 'type' => 'mobile', 'region' => 'Oceania'],
    'rheto' => ['name' => 'Rheto Payments', 'type' => 'api', 'region' => 'Oceania'],
    'mih-pay' => ['name' => 'MIH Pay', 'type' => 'api', 'region' => 'Oceania'],
    'vault-pay' => ['name' => 'Vault Payments', 'type' => 'api', 'region' => 'Oceania'],
];
